name: Build and Release Python Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy icon file
        run: cp SFS.ico dist/

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --icon=dist/SFS.ico SFS.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SFS-executable
          path: dist/SFS.exe

      - name: Get latest tag
        id: get_tag
        run: |
            git fetch --tags
            TAG=$(git describe --tags --abbrev=0)
            if [ -z "$TAG" ]; then
              echo "::set-output name=TAG_NAME::v1.0.0"  # Default to v1.0.0 if no tags are available
            else
              echo "TAG_NAME=$TAG" >> $GITHUB_ENV
            fi
        

      - name: Increment version
        id: increment_version
        run: |
            TAG_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)
            VERSION=${TAG_NAME:1}
            IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
            MAJOR="${VERSION_PARTS[0]}"
            MINOR="${VERSION_PARTS[1]}"
            PATCH="${VERSION_PARTS[2]}"
            ((PATCH++))
            NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "NEW_TAG_NAME=v$NEXT_VERSION" >> $GITHUB_ENV
        

      - name: Create GitHub Release
        id: create_github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.NEW_TAG_NAME }}
          release_name: ${{ steps.increment_version.outputs.NEW_TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_github_release.outputs.upload_url }}
          asset_path: dist/SFS.exe
          asset_name: SFS.exe
          asset_content_type: application/octet-stream
